on: [pull_request]

jobs:
  dry-code-action:
    runs-on: ubuntu-latest
    name: Dry Code
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Dry Code Action
        uses: Pposong-Hantaihe/dry-code@6e304090d89a1f69ee03dea68c049d66aabad258
        with:
          options: ''
          arguments: 'src'
          Token: "${{ secrets.GITHUB_TOKEN }}"